### ISSUE TITLE
Invalid graph name

### ISSUE THREAD

**Issue by Cycov** [ROS-Mobile/ROS-Mobile-Android#12]
### What is the issue:
When connecting to ROS master the application crashes unexpectedly. 

### Where/When:
When connecting to the ROS master

### Why
Node names contain invalid characters.
The only valid characters are a-z, A-Z, 0-9, / and _.

### Solution
1. In `BaseNode.java` replace spaces with '_', and disregard other invalid characters. 
2. When the user tries to rename the node, warn and don't let him close the rename dialog

Similar problem can be seen [here](https://answers.ros.org/question/262331/rosinvalidnameexception-error/).

**Comment by Torellin** [comment]
Solved, will be included in the update 1.1.1 bugfixes.
