### ISSUE TITLE
SSH Connection data not saved

### ISSUE THREAD

**Issue by l-schilling** [ROS-Mobile/ROS-Mobile-Android#2]
If you use the SSH tab and change the IP adress, username and password and then at some point reopen the app, the data is not saved. Instead the default ssh values are there.

**Comment by NRottmann** [comment]
Thanks for your comment. We currently work on adding this feature into the app. We will keep you updated about the progress.

**Comment by NRottmann** [comment]
Hi, SSH access data is now saved. You can download the current version of the application here:

https://github.com/ROS-Mobile/ROS-Mobile-Android/tree/Update_1.0.1

and follow up the installing instructions from here:

https://github.com/ROS-Mobile/ROS-Mobile-Android/tree/Update_1.0.1#built-from-source

Best, Nils
