### ISSUE TITLE
New versions not in Google Play Store

### ISSUE THREAD

**Issue by MichaelT64** [ROS-Mobile/ROS-Mobile-Android#22]
Hello
it seems that the new versions are not available in the Google Play Store.
The last version listed is 1.0.0 from 22th of May.

Michael

**Comment by NRottmann** [comment]
Dear Michael,
We currently fixing some last bugs (Version 1.1.1). Hopefully we will upload this Version to Google Play within this week.
Best, Nils

**Comment by NRottmann** [comment]
The current version 1.1.1 is now in the Google Play Store available.
