### ISSUE TITLE
Installing Instructions

### ISSUE THREAD

**Issue by Claudio-gh** [ROS-Mobile/ROS-Mobile-Android#27]
Congratulations on sharing this library.
I downloaded the repository to try to compile with Android Studio 4.1.1
When compiling, I always get error "> **Missing Ament Gradle property: ament.build_space**"
Is it essential to compile on the PC where ROS is installed or am I wrong something?

I apologize if this is not the right place to ask questions.

**Comment by NRottmann** [comment]
It is not required to have ROS installed. You can compile the application on any PC running the currrent Android Studio version. I would try the following steps:

Build -> Clean Project
Build -> Make Project

**Comment by Claudio-gh** [comment]
Perfect. Thanks you a lot!!
