### ISSUE TITLE
Joystick continues to send zero-velocity commands

### ISSUE THREAD

**Issue by NikolasE** [ROS-Mobile/ROS-Mobile-Android#34]
I started to test the app as it looks very useful for mapping runs or a quick state check. I noticed that the joystick continues to send cmd_vel-messages after I stopped to use the widget. These commands then interferes with other commands until I close the app.

I suggest to only send zero-commands for maybe one second after the user released the joystick to bring the robot to a stop so that normal operation (e.g via MoveBase) can be restarted with a Button-press.

**Comment by NRottmann** [comment]
Thanks for testinng. We will address this issue in the next release (probably somewhen in april) by adding a switch for either continuous publishing with a certain frequency or publishing only on change.
