### ISSUE TITLE
Detail: Red 'Disconnect'-button as feedback for succesful connection is suprising

### ISSUE THREAD

**Issue by NikolasE** [ROS-Mobile/ROS-Mobile-Android#35]
Just a minor detail, but after clicking the blue 'Connect' button I had expected a positive response from the app, but got a red 'disconnect' button which looks like a negative feedback to me. 
How about adding a 'Connection State' label next to the 'Disconnect' button?

I could have time to implement such a feature, but not in the next weeks.

**Comment by NRottmann** [comment]
We will try to add a more 'positive' feedback after successfully connect to the master in the new release (april).

**Comment by Torellin** [comment]
Improved with Version 2.0 👍🏼
