### ISSUE TITLE
Logger crashes when selecting topic name

### ISSUE THREAD

**Issue by rtb21** [ROS-Mobile/ROS-Mobile-Android#37]
Hi, great app!

Unfortunately I'm struggling with the logger viz, I find that when connected to ROS master (Noetic) and I tap on the topic name to select which one to log the app crashes.

Running version 1.2 on Android 10 

Cheers

**Comment by NRottmann** [comment]
The logger feature has been added just recently. It may be that there is still a bug in it. We will have a look and inform you here if solved.
