### ISSUE TITLE
I can't see the map in VIZ tab even ROS shows me the phone is suscribed at topic map

### ISSUE THREAD

**Issue by edrsd** [ROS-Mobile/ROS-Mobile-Android#38]
Hello, I'm newbie in ROS and I'm doing this tutorial "https://github.com/samialperen/oko_slam/blob/master/doc/hector_slam_tutorial.md"
 about SLAM. I have connected the phone sussesfully to Master and I can move the robot with Joystick but in Viz tab doesn't show the map. I have wroten the rostopic info map command and shows me the phone suscribed to the topic map. what could be going wrong? Thanks in advance.

**Comment by NRottmann** [comment]
Probably you did not set the network parameter correctly. Please check out https://github.com/ROS-Mobile/ROS-Mobile-Android/wiki/FAQ on how to set your ROS network parameters correctly. Please then tell us if that solved your problem.

**Comment by edrsd** [comment]
thanks a lot you were right. I used this "https://answers.ros.org/question/206876/how-often-do-i-need-to-source-setupbash/" 
to wrote in .bashrc file and add this two lines:
export ROS_IP="MY_PC_IP"
export ROS_MASTER_URI=http://"MY_PC_IP":11311

I have another question: Is there a way to show the robot's position on the map? because for now I can only see how the map is created without seeing a robot reference. Again thank a lot NRottmann.

**Comment by NRottmann** [comment]
You are welcome, The feature of showing the robots pose will be added within the next month by my colleague.

**Comment by jack162** [comment]
Hello, could you tell me how to set the network parameter?  i know how to set in pc, but i don't how where is .bashrc file in Android devices. Thanks a lot.

**Comment by Torellin** [comment]
There is none. You only have to set the ROS variables on the master Pc and connect to it via the same network. Additionally try to ping your phone/tablet - if this is successful you should be good to go.

**Comment by jack162** [comment]
yes,i set the variables as below in master pc

**export ROS_HOSTNAME=192.168.50.77
export ROS_MASTER_URI=http://192.168.50.77:11311
ROS_IP=192.168.50.77**

but in my android device still can't recevice any messenges
(btw, i have try to check the node connection by "rosnode info ..." 
it shows the device node has subscribe to rostopic(/map)   )

**Comment by NRottmann** [comment]
Does the joystick not connect or does it not send any data. In the first case, it might be still an issue with the network parameter. In the second case you might have some issues with existing firewalls or network permissions.

**Comment by jack162** [comment]
oh,that is second case.
The firewalls or network permissions for pc or android device?
