### ISSUE TITLE
Questions about the communication module

### ISSUE THREAD

**Issue by KainanSu** [ROS-Mobile/ROS-Mobile-Android#39]
The paper( [ROS-Mobile: An Android application for the Robot Operating System](https://arxiv.org/abs/2011.02781v1) ) points out that rosJava is limited to older Android versions, so why not design a communication module based on the [rosbridge protocol](https://github.com/RobotWebTools/rosbridge_suite/blob/groovy-devel/ROSBRIDGE_PROTOCOL.md)?

**Comment by NRottmann** [comment]
We rewrote rosJava such that it is now fully functional with current Android versions. However, using the rosbridge protocol might be also possible and we might have a look into that in the near future.
