### ISSUE TITLE
Rviz launch error

### ISSUE THREAD

**Issue by dineshrampalli** [ROS-Mobile/ROS-Mobile-Android#41]
I am trying to run differential robot with gmapping from mobile teleop is working but the map is not displaying I'm getting qt error
![Screenshot_20210316-112501](https://user-images.githubusercontent.com/64398404/111262682-ab070d00-864a-11eb-872e-ea9c8fffe518.jpg)

**Comment by dineshrampalli** [comment]
Solved by export roshostname

**Comment by Torellin** [comment]
This seems to be a problem of your ROS navigation stack and not of the ROS-Mobile App. I recommend checking your launch scripts according to the ROS website and tutorials.

**Comment by Torellin** [comment]
Nice, thanks for the update!
