### ISSUE TITLE
Viz error

### ISSUE THREAD

**Issue by dineshrampalli** [ROS-Mobile/ROS-Mobile-Android#42]
![Screenshot_20210316-170531](https://user-images.githubusercontent.com/64398404/111302853-e4a33c80-8679-11eb-82f3-4ac83601411d.jpg)
![Screenshot_20210316-170533](https://user-images.githubusercontent.com/64398404/111302861-e66d0000-8679-11eb-8bbb-ade2d4847cd3.jpg)
Why sometimes it's not working.

**Comment by Torellin** [comment]
This could be due to several things. 
Please check if: 
1. Connection to Master is established
2. Environment variables are set correctly in the .bashrc e.g. ROS_MASTER_URI etc.
3. The topic name and type of the Camera widget is equal to the published topic

**Comment by dineshrampalli** [comment]
Solved it thanks
