### ISSUE TITLE
Not able to visualize SLAM from rviz on the mobile app on topic /map

### ISSUE THREAD

**Issue by arielsanchez2018** [ROS-Mobile/ROS-Mobile-Android#43]
Have a similar issue than this closed one: #38 https://github.com/ROS-Mobile/ROS-Mobile-Android/issues/38  and its solution of editing the bashrc file (with the commands from issue #38 of exporting ROS_IP and Master URI using this https://answers.ros.org/question/206876/how-often-do-i-need-to-source-setupbash/ did not work for me . I am attaching it as well The ROS1 melodic is installed on a raspberry pi 4 utilizing lidar sensor rplidar A1 . The SSH and Master URI are able to successfully connect. I run roscore before anything and utilized the commands for export ROS_IP , export ROS_MASTER_URI and export ROS_HOSTNAME. I am able to successfully export to a pc with ROS installed and see the rviz simulation from there. Is there anything that I could be doing wrong with the subscription to the topics in rviz ? 
Do you have an image on how it should display the map topic on the gridMap with SLAM ?
Thanks for the help

![163221971_471159194031564_7394904368186905718_n](https://user-images.githubusercontent.com/64445868/112547300-f9c24e80-8d90-11eb-9d27-b1471942efdf.jpg)
![163062268_172485101364986_2164913282364909108_n](https://user-images.githubusercontent.com/64445868/112547301-fa5ae500-8d90-11eb-92a4-9be06eef2dd8.jpg)
![164351907_3226670950768708_3243319609594789390_n](https://user-images.githubusercontent.com/64445868/112547303-fa5ae500-8d90-11eb-8c95-8cae24ee4e4a.jpg)
![164483762_452765199367656_5653779375901678839_n](https://user-images.githubusercontent.com/64445868/112547304-faf37b80-8d90-11eb-93a2-fb62b93fcd9e.jpg)
![163076921_406538924102128_6497237695942040200_n](https://user-images.githubusercontent.com/64445868/112547309-faf37b80-8d90-11eb-9841-e70d24adc9a8.jpg)
![164826803_155643959755297_1304684363003790482_n](https://user-images.githubusercontent.com/64445868/112547311-fb8c1200-8d90-11eb-8c7c-54efe90f6b45.jpg)
![163634538_144491580916717_6539565642695079646_n (1)](https://user-images.githubusercontent.com/64445868/112547312-fc24a880-8d90-11eb-8f43-cfb0758aeb5d.jpg)

**Comment by NRottmann** [comment]
Probably you did not choose the topic from the drop down list. It seems that the default topic is chosen. Even if your map topic has the same name, you need to choose a topic from the drop down menu once. Also, please consider updating your app to the latest version.
