### ISSUE TITLE
Subscribing to tf messages from widgets

### ISSUE THREAD

**Issue by shantanuwasu** [ROS-Mobile/ROS-Mobile-Android#49]
Hi ,
I have added widgets which can display odometry and Lidar data in view tab. Now I want to subscribe to tf messages
which will be used in all other sensors data widgets like odometry, lidar etc
So, I want to know that , is there any way to receive 2 different ros msg types in single widget or else, 
is it possible to receive tf message in new widget and which can communicate with other widgets to transfer data?? 

Thanks in advance .

**Comment by Torellin** [comment]
Hey,
we will publish a new layer system which is capable of subscribing to TF topic as well in the next few days. In Version <2.0 it is not that easy to get a subscription to multiple topics simultaneously. So be prepared to update :)
