### ISSUE TITLE
Connection fail beacuse of firewall issue in ubuntu

### ISSUE THREAD

**Issue by dineshrboson** [ROS-Mobile/ROS-Mobile-Android#53]
![Screenshot from 2021-05-25 12-58-50](https://user-images.githubusercontent.com/77951479/119458247-2a574200-bd5a-11eb-873f-5969613b7efe.png)
![Screenshot from 2021-05-25 13-07-20](https://user-images.githubusercontent.com/77951479/119458255-2c210580-bd5a-11eb-8e09-1075ac0a4108.png)

**Comment by dineshrboson** [comment]
![Screenshot_20210525-130534](https://user-images.githubusercontent.com/77951479/119458393-54a8ff80-bd5a-11eb-9506-d48ca92b5891.jpg)
![Screenshot_20210525-130530](https://user-images.githubusercontent.com/77951479/119458395-5672c300-bd5a-11eb-8ac1-ac79e34da00b.jpg)
![Screenshot_20210525-130527](https://user-images.githubusercontent.com/77951479/119458398-570b5980-bd5a-11eb-9aa5-26b44695c8f9.jpg)

**Comment by dineshrboson** [comment]
![Screenshot_20210525-131000](https://user-images.githubusercontent.com/77951479/119458582-89b55200-bd5a-11eb-8598-845a90f7e1f8.jpg)

**Comment by dineshrboson** [comment]
I used this app previously with same kind of procedure but now it's little bit confusing can anyone help me out

**Comment by Torellin** [comment]
Have you set the environment variables in the bashrc?

**Comment by Torellin** [comment]
And maybe try again with Mobile Data disabled. Normally it should work fine, but we have also encountered some issues while being connected to multiple networks simultaneously. For that we have introduced the device ip chooser which you can see in your last image.

**Comment by dineshrboson** [comment]
![Screenshot_20210526-094455](https://user-images.githubusercontent.com/77951479/119601606-20d7e380-be07-11eb-830f-36d3281caacb.jpg)
![Screenshot_20210526-094451](https://user-images.githubusercontent.com/77951479/119601612-22a1a700-be07-11eb-95f9-5d53b814991e.jpg)
![Screenshot_20210526-094346](https://user-images.githubusercontent.com/77951479/119601615-233a3d80-be07-11eb-9332-0ea3054a4d5a.jpg)
![Screenshot_20210526-094340](https://user-images.githubusercontent.com/77951479/119601619-233a3d80-be07-11eb-89e8-fd43dc439d7b.jpg)
![Screenshot_20210526-094338](https://user-images.githubusercontent.com/77951479/119601621-23d2d400-be07-11eb-9fcd-8f6904c6f85a.jpg)

**Comment by dineshrboson** [comment]
![Screenshot from 2021-05-26 09-51-52](https://user-images.githubusercontent.com/77951479/119602100-10743880-be08-11eb-8d03-335fff9eb7e3.png)

**Comment by dineshrboson** [comment]
I hope I tried every possible way.

**Comment by dineshrboson** [comment]
![Screenshot from 2021-05-26 09-53-56](https://user-images.githubusercontent.com/77951479/119602212-4f09f300-be08-11eb-98be-bab2fb3a4229.png)

**Comment by Torellin** [comment]
Ok this is indeed very strange. Did you have the environment variables before or are they newly added?

**Comment by dineshrboson** [comment]
I just added them newly and tried

**Comment by Torellin** [comment]
So you have to source the new variables first. As the latest picture indicated, you tried but entered the wrong file. Open a new Terminal should remove this issue.

**Comment by dineshrboson** [comment]
![Screenshot from 2021-05-26 11-17-53](https://user-images.githubusercontent.com/77951479/119608709-09532780-be14-11eb-8b8e-9a9905e1d3b8.png)

**Comment by dineshrboson** [comment]
![Screenshot_20210526-111825.jpg](https://user-images.githubusercontent.com/77951479/119608772-24be3280-be14-11eb-9c1a-acb9fc897211.jpg)

**Comment by dineshrboson** [comment]
Not working.

**Comment by Torellin** [comment]
Ok well.. let me think about this a sec.

**Comment by Torellin** [comment]
Are you running roscore on an emulator or virtual environment?  I'm grasping at straws..

**Comment by dineshrboson** [comment]
I made my mac into ubuntu and running ros on it.

**Comment by dineshrboson** [comment]
no virtual env though

**Comment by Torellin** [comment]
Can you ping your phone from your device?

**Comment by dineshrboson** [comment]
let me try please

**Comment by dineshrboson** [comment]
dinesh@dinesh-MacBookAir:~$ ping 192.168.0.100
PING 192.168.0.100 (192.168.0.100) 56(84) bytes of data.
64 bytes from 192.168.0.100: icmp_seq=1 ttl=64 time=20.5 ms
64 bytes from 192.168.0.100: icmp_seq=2 ttl=64 time=46.2 ms
64 bytes from 192.168.0.100: icmp_seq=3 ttl=64 time=69.8 ms
64 bytes from 192.168.0.100: icmp_seq=4 ttl=64 time=103 ms
64 bytes from 192.168.0.100: icmp_seq=5 ttl=64 time=3.06 ms
64 bytes from 192.168.0.100: icmp_seq=6 ttl=64 time=34.4 ms
64 bytes from 192.168.0.100: icmp_seq=7 ttl=64 time=61.0 ms
64 bytes from 192.168.0.100: icmp_seq=8 ttl=64 time=86.2 ms

**Comment by dineshrboson** [comment]
yes I guess

**Comment by dineshrboson** [comment]
can you briefly describe steps to connect so that I will try to repeat from starting.

**Comment by Torellin** [comment]
In other words, you can confirm all the items in the connection help list in the app?

**Comment by dineshrboson** [comment]
valid and active WIFI connections?
YES 
Correct IP and PORT of the ROS MASTER entered?
Don't KNOW  hopefully yes
Is this device in the same network as the Master system?
YES
Changed the environment variables of the Master system?
Dont know hopefully yes
Master is running?
Yes. Roscore

**Comment by Torellin** [comment]
Try reinstalling the app. Make sure that you are connected to the same network as your roscore and that only your WiFi on your phone is enabled.
On the Master Pc:
Find your IP with ifconfig, copy it into the ROS env variables in your bashrc. Open a freshly new terminal and try to resolve error messages like the one above by removing the "SLAM"-line from the bashrc and other duplicate lines.
Start the roscore and make sure that the Master IP matches the one entered in the bashrc.
Ping the phone for a quick check.

Enter the correct Master IP on ROS-Mobile.
Now it should hopefully connect.

**Comment by dineshrboson** [comment]
can you elaborate ROS_ENV variables ?
is it refers to ROS_HOSTNAME= ip add
or ROS_IP=ip
orROS_Maste r_URI=ip
which of these I need to add?
or all of these?

**Comment by Torellin** [comment]
`
myIp=192.168.178.62
export ROS_IP=$myIp
export ROS_HOSTNAME=$myIp
export ROS_MASTER_URI=http://$myIp:11311
`
This is what I have in my bashrc.

**Comment by dineshrboson** [comment]
![Screenshot from 2021-05-26 12-00-51](https://user-images.githubusercontent.com/77951479/119612886-11ae6100-be1a-11eb-8d96-95e156f12778.png)

**Comment by dineshrboson** [comment]
removed duplicates and error SLAM

**Comment by Torellin** [comment]
I don't like to ask, but have you tried other ROS apps for Android and did it work there?

**Comment by dineshrboson** [comment]
yeah while I was in my monitor it worked and I am using my personal laptop Its not working

**Comment by dineshrboson** [comment]
![Screenshot_20210526-120326.jpg](https://user-images.githubusercontent.com/77951479/119613249-694ccc80-be1a-11eb-8641-55bb5232c06b.jpg)

**Comment by dineshrboson** [comment]
You see that this is another app and it is also not working

**Comment by dineshrboson** [comment]
previously It worked with another machine

**Comment by Torellin** [comment]
Ok, luckily we can confirm that it is not the app ^^

**Comment by dineshrboson** [comment]
haha cool :100:

**Comment by dineshrboson** [comment]
none of the apps are connecting to my roscore I dont know whats the issue

**Comment by dineshrboson** [comment]
![Screenshot from 2021-05-26 12-04-59](https://user-images.githubusercontent.com/77951479/119613519-c9dc0980-be1a-11eb-8f78-b368e4c4d969.png)

**Comment by dineshrboson** [comment]
and if I connect though mobile its not connecting

**Comment by Torellin** [comment]
What is the content of your "/etc/hosts" file?

**Comment by dineshrboson** [comment]
![Screenshot from 2021-05-26 12-11-56](https://user-images.githubusercontent.com/77951479/119614173-977edc00-be1b-11eb-8c60-71544f60a37d.png)

**Comment by Torellin** [comment]
Seems ok I guess. What about running "roswtf" in a second terminal after starting the roscore?

**Comment by dineshrboson** [comment]
![Uploading Screenshot from 2021-05-26 12-15-14.png…]()

**Comment by dineshrboson** [comment]
![Screenshot from 2021-05-26 12-15-14](https://user-images.githubusercontent.com/77951479/119614586-12e08d80-be1c-11eb-9e70-2494687240fa.png)

**Comment by Torellin** [comment]
Another thing: Can you confirm the same timezone and clock time of your two devices?

**Comment by dineshrboson** [comment]
Yes 12:18 WED MAY26 2021
12:18 WED MAY26 2021
in both devices

**Comment by Torellin** [comment]
I'm slowly running out of my expertise. The problem could be that you are running ROS on a laptop and the network setup is somewhat different.

**Comment by dineshrboson** [comment]
Yeah That's Fine I will try to resolve the issue.
Thanks for your patience and help

**Comment by dineshrboson** [comment]
Hey just to make sure it helps you 
I had firewall in my machine installed longback ufw I looked at rosnetworksetup and disable firewall and uninstalled it and now its working

**Comment by dineshrboson** [comment]
Thanks again man.

**Comment by dineshrboson** [comment]
please close the issue when you see it.
