### ISSUE TITLE
I want to connect jetson nano and android application via bluetooth. 

### ISSUE THREAD

**Issue by soyeon219** [ROS-Mobile/ROS-Mobile-Android#54]
I want to connect jetson nano and android application via bluetooth. The signal(result of deeprunning) comes from the jetson nano to the smartphone, and I want to run the application according to the signal. Is there any way?

**Comment by Torellin** [comment]
Is the signal  in a ROS-compatible format? Then potentially yes.

**Comment by soyeon219** [comment]
Yes, we refer to this site for training. 
https://github.com/dusty-nv/jetbot_ros

But I'm not sure how to signal from ros device to smartphone.

**Comment by Torellin** [comment]
Please take a look at the ROS Networking Setup on their website. 
http://wiki.ros.org/ROS/NetworkSetup
The App only works if it can connect to a ROS-core and available topics.

**Comment by NRottmann** [comment]
Forwarded to ROS network setup.
