### ISSUE TITLE
Connecting to Localhost roscore with Android emulator

### ISSUE THREAD

**Issue by lelliott20s** [ROS-Mobile/ROS-Mobile-Android#56]
Is there a way to connect to a roscore on my localhost while running the app via the Android studio emulator? I set the Master URL to be 10.0.2.2 which according to the documentation reroutes to where localhost is. On my local machine I see the topics showing up, but topic data doesn't seem to be going between the two. Thanks!

**Comment by Torellin** [comment]
Hey, the Master Url has to be set according to the network setup on the official ROS website. But it seems that one can only subscribe to topics. Publishing from the emulator does not work. We haven't figured out what exactly the problem is. Sorry to tell you that!
