### ISSUE TITLE
GirdMap isn't Display For  origin: [-5.250000, -5.050000, 0.000000]  of file .yaml

### ISSUE THREAD

**Issue by caiyahui** [ROS-Mobile/ROS-Mobile-Android#63]
In navigation mode，For the topic of /map ,GirdMap isnot Display;

Modify the contents of  file .yaml, 
Change  origin: [-5.250000, -5.050000, 0.000000]  of file .yaml to origin: [-0.000000, -0.000000, 0.000000]  of file .yaml ,the topic of /map ,GirdMap is Display OK;

Excuse me, why can't  origin: [-5.250000, -5.050000, 0.000000]  of file .yaml  ,the topic of /map ,GirdMap isn't Display

**Comment by Torellin** [comment]
This seems to be a general ROS question/comment and not particular about the app, or do I get this wrong?

**Comment by caiyahui** [comment]
the problem of origin: [-5.250000, -5.050000, 0.000000] of file .yaml  is that the Android Apps Map NAV does not exist，Will it be the problem of the app gird map  analysis

**Comment by Torellin** [comment]
Can you send the content if this yaml-file?

**Comment by caiyahui** [comment]
Hi All:


The attachment for the map.pgm and&nbsp;map.yaml



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ROS-Mobile/ROS-Mobile-Android"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月11日(星期天) 上午9:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ROS-Mobile/ROS-Mobile-Android] GirdMap isn't Display For  origin: [-5.250000, -5.050000, 0.000000]  of file .yaml (#63)





 
Can you send the content if this yaml-file?

**Comment by caiyahui** [comment]
Hi

Map





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ROS-Mobile/ROS-Mobile-Android"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月11日(星期天) 上午9:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ROS-Mobile/ROS-Mobile-Android] GirdMap isn't Display For  origin: [-5.250000, -5.050000, 0.000000]  of file .yaml (#63)





 
Can you send the content if this yaml-file?

**Comment by caiyahui** [comment]
Use the App of ROS-Mobile-Android and  Map NAV to display different effects for  the File of map.pgm and map.yaml;
the App of ROS-Mobile-Android  display :
![1](https://user-images.githubusercontent.com/45075122/125245557-4b342080-e323-11eb-9df3-14c29ffd0815.png)
![2](https://user-images.githubusercontent.com/45075122/125245561-4c654d80-e323-11eb-92e6-e4a9dc6677ef.png)
![3](https://user-images.githubusercontent.com/45075122/125245567-4d967a80-e323-11eb-96dc-18e84122822d.png)
the App of  Map NAV  display :
![4](https://user-images.githubusercontent.com/45075122/125245608-5a1ad300-e323-11eb-9b89-ce430a2b8140.png)


the File of map.pgm and map.yaml
[map.zip](https://github.com/ROS-Mobile/ROS-Mobile-Android/files/6799318/map.zip)

**Comment by Torellin** [comment]
The laserscan seems ok. Is the map subscribed? Can you share the Widgets list as well as the Layer list of the TF Viz in the Details Tab?

**Comment by Torellin** [comment]
Alright, can you confirm that on the \map-topic a nav_msgs/OccupancyGrid is published? The App doesn't know about your yaml files. It only subscribes to the map-topic and also get all necessary infos from the message. If there is something missing, the app cannot display the map correctly.

**Comment by caiyahui** [comment]
![image](https://user-images.githubusercontent.com/45075122/125445702-2bc393e5-d91e-46eb-9b24-eaf80e55cb63.png)
![image](https://user-images.githubusercontent.com/45075122/125445813-6e381ac8-7827-453e-b13f-e05da811c483.png)

**Comment by NRottmann** [comment]
We have an idea what the problem might be. We will check it within the next days and come back to you.

**Comment by NRottmann** [comment]
Please try out the current Development Branch. We hope that this fixed your problem. For building the app from source, follow the instructions here: https://github.com/ROS-Mobile/ROS-Mobile-Android#built-from-source

**Comment by caiyahui** [comment]
The result is the same ，Try out the current Development Branch.   

Sync with apply from: "https://github.com/rosjava/rosjava_bootstrap/raw/kinetic/buildscript.gradle"

Where is the change between the current Development Branch and before.

**Comment by NRottmann** [comment]
For messages like \map, most often we only receive a message at the start of the node subscription. The problem is that we are not storing any last message data, thus at the first initialization of the view the map data is received and the map is displayed. By changing now the tab and going back, the view is destroyed and restored. But since we already received a message, we can not restore the data. To solve this issue, we now store the last message for a subscriber such that we can rebuild the view.

I thought that this could have been your problem, but it seems that there is another. My best guess now is that there is an issue with the TFs.

**Comment by caiyahui** [comment]
In one case, /map is displayed，The car at two points in the actual navigation process。
But I stopped navigating, or didn't start navigating, changed messages  \map，After adjusting back to  \map it also does not show。
In the case of \map display, WIGETS multiple layers will also cause the map to not be displayed

**Comment by caiyahui** [comment]
The car at two points in the actual navigation process。
messages \map display error, messages \move_bass display ok
![1](https://user-images.githubusercontent.com/45075122/126770542-741d1088-8416-46e1-ba3b-11c88f950f9a.png)
![2](https://user-images.githubusercontent.com/45075122/126770548-5462c8bd-adba-4e9b-a3f8-afe9d3eaebae.png)
![3](https://user-images.githubusercontent.com/45075122/126770552-f97f3ee4-d29c-42f0-9a88-7e7335d8e0fe.png)

**Comment by NRottmann** [comment]
Do you have a GitHub Repo from which we can download your simulation to reproduce the error?

**Comment by caiyahui** [comment]
Just use the latest version，What's the difference between  messages \map and messages \move_bass

**Comment by NRottmann** [comment]
In order to be able to help you solve your problem, we need to recreate the error. Therefore, we need you simulation environment and a description how to reproduce the error. Then we can debug it and probably solve it.

\map and \move_base are not message, they are topics which provide some specific messages. \map provides thereby most often a nav_msgs/OccupancyGrid message.

**Comment by caiyahui** [comment]
Hi NRottmann:
Thank you for following up, Part of the content is not displayed;
Use your latest ROS-Mobile-Android app-release.apk testing;

GUI for Details and Widgets :
![image](https://user-images.githubusercontent.com/45075122/126972770-5d9eedc7-81e2-4409-8442-d4e3ec6163f3.png)

file of .pgm and .yaml
[map.zip](https://github.com/ROS-Mobile/ROS-Mobile-Android/files/6877393/map.zip)

mapping  mode:
![image](https://user-images.githubusercontent.com/45075122/126972904-ef0d206c-db60-49a7-8896-9b4406756d24.png)

nav. mode(Circular navigation between two points):
display ok:
![image](https://user-images.githubusercontent.com/45075122/126972958-19142b99-fcef-4915-ac73-abd555d22495.png)

display error:
![image](https://user-images.githubusercontent.com/45075122/126972988-844b25a2-9753-4c80-a728-a98507c2acc0.png)

**Comment by caiyahui** [comment]
> In navigation mode，For the topic of /map ,GirdMap isnot Display;
> 
> Modify the contents of file .yaml,
> Change origin: [-5.250000, -5.050000, 0.000000] of file .yaml to origin: [-0.000000, -0.000000, 0.000000] of file .yaml ,the topic of /map ,GirdMap is Display OK;
> 
> Excuse me, why can't origin: [-5.250000, -5.050000, 0.000000] of file .yaml ,the topic of /map ,GirdMap isn't Display
