### ISSUE TITLE
Joystick not working

### ISSUE THREAD

**Issue by GodMiu-6789** [ROS-Mobile/ROS-Mobile-Android#66]
Dear team,
I just installed the app on my android emulator (android 5.1). I am using raspberry pi running on Ubuntu 18.04 (supported by ros melodic). I am trying to use joystick to teleop my robot .However, after successfully connecting the app with my pi (I can do rostopic list and i see /cmd_vel ), the joystick seems not to publish any Twist msg (I echo /cmd_vel). Can anyone help me please ? I really appreciate it !
Regards,
GodMiu

**Comment by NRottmann** [comment]
Is the joystick registered to the /cmd_vel topic? Thus, if you typing
````
rostopic info /cmd_vel
````
does the joystick node appear as publisher? If so and when no messages are poblic, make first sure that all ROS network parameters are set probably.

**Comment by GodMiu-6789** [comment]
Dear NRottmann,
Thank you for your response! Yes I did rostopic info /cmd_vel and there is a node called /cmd_vel shown as a publisher. I guess that is what you meant by joystick node. Can you explain more on what should be the network parameters to be set. I 
Regards,
GodMiu

**Comment by GodMiu-6789** [comment]
I also want to add that I did set the Master Url and the right port.

**Comment by GodMiu-6789** [comment]
Dear NRottmann,
Thank you for your response! Yes I did rostopic info /cmd_vel and there is a node called /cmd_vel shown as a publisher. I guess that is what you meant by joystick node. Can you explain more on what should be the network parameters to be set. I
Regards,
GodMiu

**Comment by GodMiu-6789** [comment]
![image](https://user-images.githubusercontent.com/83930020/128214545-0d23ebd6-2d96-4e51-bce8-d9158c656532.jpeg)
To make it more clear, this the what I see in terminal

**Comment by GodMiu-6789** [comment]
![image](https://user-images.githubusercontent.com/83930020/128214781-4f232dda-8606-45d3-955a-d858c4095895.jpeg)
This is what I see in terminal.

**Comment by NRottmann** [comment]
The network parameter settings are explained here
https://github.com/ROS-Mobile/ROS-Mobile-Android/wiki/FAQ

**Comment by amjack0** [comment]
May be try, deleting the Joystick widget and add again. This worked for me !

**Comment by GodMiu-6789** [comment]
Thanks man, I have completed my project for 8 months with a high mark. Btw, thank you for ur recommendation!
