### ISSUE TITLE
Issue with compressed image subscription

### ISSUE THREAD

**Issue by liver121888** [ROS-Mobile/ROS-Mobile-Android#67]
I am testing a webcam for my robot. I am using a virtual machine with ubuntu 18.04 to ssh the actual robot. The robot is jetson nano equipped with ubuntu 18.04, too. Now I was trying to hook up the app to the machine. The /cmd_vel works fine, but the camera is not working. I check for some issues on the board and I make sure that ufw is down.
First, my cam is working(view from virtual ubuntu):
![image_view](https://user-images.githubusercontent.com/68542467/128638404-abd9f0e2-a051-4c39-b9bc-2d7826e54632.png)
And here is my config(clbrobot is the real robot, while ubuntu is the virtual machine, g3226 is my phone):
![etc and bashrc](https://user-images.githubusercontent.com/68542467/128638376-65432fc0-88c9-4798-beca-1c8acb9f1aca.png)
the machine can ping each other(I am not familiar with android so I don't know how to ping in android environment)
![pinging](https://user-images.githubusercontent.com/68542467/128638464-bdf41c17-40c3-4faf-88cf-750cbbecf3d7.png)
rosnode list and rostopic list
![list](https://user-images.githubusercontent.com/68542467/128638509-033bbd7a-c799-4807-b4e1-d7076ffc1d9e.png)
rosgraph and roswtf
![rosgraph2](https://user-images.githubusercontent.com/68542467/128638764-795f833e-295c-4f02-a941-2dcf2d2c7452.png)
![wtf](https://user-images.githubusercontent.com/68542467/128638494-8abff5d6-bf94-48f1-ac8e-658ad200db6f.png)
so when I get to the info I get this:
![info](https://user-images.githubusercontent.com/68542467/128638528-3dee07a1-8f2d-4723-bcdd-3b83ec4ec725.png)
The node can contact each other however the topic is not transmitted inbound to the node. I am confused.
I am having a hard time looking for the answer, they always link to the network and multiple machine tutorial page.
It is my first time writing stuff like this so maybe the question sounds silly but please help me because I have been stuck here for like two weeks. 😢

**Comment by liver121888** [comment]
And here is the config on the phone:
![Screenshot_20210808-234236](https://user-images.githubusercontent.com/68542467/128638935-488a2dcb-866d-4c19-98e9-d0e7a2d58e08.png)
the phone can ssh clbrobot
![Screenshot_20210808-234406](https://user-images.githubusercontent.com/68542467/128638939-dc13d101-63a5-435e-840a-0feed78c3f66.png)
camera setting
![Screenshot_20210808-234418](https://user-images.githubusercontent.com/68542467/128638948-d576904e-1be8-401e-8103-12196524d920.png)

**Comment by Torellin** [comment]
I can only guess what the problem could be, but probably it is your exported ROS_MASTER_URI with your local address "clbrobot". Please try to follow the convention with 
```
ROS_IP=<masterIP>
ROS_HOSTENAME=<masterIP>
ROS_MASTER_URI=http://<masterIP>:11311
```
on ther Master Pc.
Also make sure you can confirm all other bullet points which pop up inside the App on the Master page.

**Comment by liver121888** [comment]
The problem is solved, and everything works fine. Thank you for helping me out!

**Comment by PlainJi** [comment]
same problem and solved. Tks!
As ROS mobile can't resolve the self-defined hostname, we should use IP directly for ROS_HOSTNAME.
Doesn't matter for ROS_IP and ROS_MASTER_URI.
