### ISSUE TITLE
Welcome to ROS-Mobile-Android Forum!

### ISSUE THREAD

**Issue by mum2** [ROS-Mobile/ROS-Mobile-Android#78]
I'm going to use this app to control the robot. I want to send the robot to a predetermined location rather than real-time control, is there a way? Or can I send a message designated as the master pc? I'd appreciate it if you could help me.

**Comment by Torellin** [comment]
Hey, of course it's possible. Take a look at some tutorials about navigation with ROS. E.g. here: http://wiki.ros.org/navigation/Tutorials
