### ISSUE TITLE
Compressed image not showing

### ISSUE THREAD

**Issue by P4STA** [ROS-Mobile/ROS-Mobile-Android#81]
Hello, I'm publishing a compressed image from a raspicam_node on my robot. 
I can see the image through rqt image view widget, so I know it is being published. 
However, the app is showing no image. The topics are set up properly. Connection works as well since I can publish cmd_vel with the joystick. 

Any idea what could be the cause? 

EDIT: the raspicam_node has a parameter enable_raw that makes it publish a sensor_msgs/Image message alongside the compressed image. When I enable it and try to show the image in ROS-mobile, it doesn't work either. Therefore the issue is probably not related to the compressed image, but there is some other more generic cause. 
I will try it with a usb webcamera instead of the raspberry pi camera to see if it is caused by the raspicam_node or something else. Still, I can see both compressed and original image just fine in rqt.

**Comment by nicostudt** [comment]
Hey,

There are multiple possible reasons for this issue. The obvious one would be a simple connection error in some way. To check that, you could try to subscribe to another topic that is not an image like a Twist message or a simple String message with the Logger/Debug widget and then check if that messages are received.

**Comment by nicostudt** [comment]
In most cases that we know where one can send but not receive messages there is an issue with the system ROS variables which has to be set like the MASTER_URI.

**Comment by P4STA** [comment]
Yes, it was the ROS_MASTER_URI. I've used an already made SD card image with preinstalled ROS. And even though I set up ROS_MASTER_URI and ROS_IP by hand into the .bashrc, the roscore still refused to start with those parameters. I had to disable some startup scripts before it started working. So nothing related to ROS-mobile after all.
