### ISSUE TITLE
Can't connect to ROS Master URI

### ISSUE THREAD

**Issue by andgomyel** [ROS-Mobile/ROS-Mobile-Android#82]
Hi!
I just tried to use your app, but when i press connect after writing both my PC and smartphone IPs, I can't connect to my PC roscore. I don't know why this is happening and if you can help me to fix it. (Maybe it's not a problem with your app but with my WiFi or ROS, I don't know)

Thanks for your help.

**Comment by nicostudt** [comment]
Hey!
I encourage you to follow the setup at http://wiki.ros.org/ROS/NetworkSetup. Most of the connection problems are due to missing system variables.

I hope this will help you!
