### ISSUE TITLE
Could not get resource 

### ISSUE THREAD

**Issue by cuihaifengchina** [ROS-Mobile/ROS-Mobile-Android#85]
hello, i am in china  clone this project with VPN， when  i build it ，get error Could not get resource

Build file 'D:\work\ROS-Mobile-Android\build.gradle' line: 6

A problem occurred evaluating root project 'RosAndroid'.
> Could not get resource 'https://github.com/rosjava/rosjava_bootstrap/raw/kinetic/buildscript.gradle'.
   > Could not GET 'https://github.com/rosjava/rosjava_bootstrap/raw/kinetic/buildscript.gradle'.
      > Connect to github.com:443 [github.com/20.205.243.166] failed: Connection timed out: connect

how to fix this？ thanks

**Comment by cuihaifengchina** [comment]
way to go! @nicostudt  thanks

**Comment by nicostudt** [comment]
Resolved in #86
