### ISSUE TITLE
Unable to drive the mobile base forward and reverse due to thin GUI interface

### ISSUE THREAD

**Issue by amjack0** [ROS-Mobile/ROS-Mobile-Android#88]
Hi,

I am using the ROS Mobile app for publishing the `/cmd_vel` to drive the mobile base. I am able to connect the app with the master and able to drive the robot. 
My issue is `I am unable to drive the robot in a pure forward and backward movement`. Because I can not keep the round knob in a straight line with the **VERY THIN VERTICAL AXIS** in a GUI.

Am I missing something here ? 

ROS Noetic + 20.04 LTS
Android device: Samsung Galaxy Tab S T800 [https://www.amazon.de/Samsung-Tablet-PC-interner-Speicher-Bluetooth-grau/dp/B00R48MCFC](url)

![ROSmobile](https://user-images.githubusercontent.com/52165935/163181300-e08990d9-b56a-46f7-b3a5-47571e5324d8.png)

**Comment by nicostudt** [comment]
Thanks for pointing this out! 
As you said, it is nearly impossible to keep the knob at a zero degree angle to the vertical axis. 
I had the idea to introduce a new joystick mode like a "sticky axis" which would publish only one of the axis values.

In the meantime you could filter the axis you dont want on the ROS side.

**Comment by amjack0** [comment]
Hi @nicostudt, 
Thanks for your support.

`In the meantime you could filter the axis you dont want on the ROS side.`
Can you explain, What do you mean by this ?

**Comment by nicostudt** [comment]
For example write an additional node that republishes /cmd_vel on a new topic but only with the values you want.

**Comment by nicostudt** [comment]
Give me a minute. I'll try to write you the necessary code for the node.

**Comment by nicostudt** [comment]
Of cause you can change the input/output topics, the axis you use and the "threshold". The threshold simulates the area in the picture you mentioned above.
I assumed both of your axis have values between -1 and 1, but feel free to remove the threshold variable and put in your numbers.

**Comment by nicostudt** [comment]
> both of your axis have values between -1 and 1
... and are centered around 0

**Comment by nicostudt** [comment]
Gern geschehen :)

**Comment by amjack0** [comment]
I resolved the issue with,

take the turn only when, `if (abs(msg.angular.z) > abs(msg.linear.x))`: is true. Else I drive forward and backward. 
With this I can do PURE forward and backward motion. 

You can close the issue, if you like.
Thank you ;)
